#!/bin/bash

# SOME FUNCTIONS HAVE CHANGED!
# --excite [tstart] [tend] [magnitude]
# This stimulates the neuron with [magnitude] pA. Example --excite 1 6 30
# --plotall Plots all relevant ion channel fluxes, ion concentrations, volumes and membrane potentials
# --plot [dict]
# This plots all components in a single figure
# dict is written as follows in this sh file: '{\"title\":[\"quantity1\",\"quantity2\"],\"title2\":[\"quantity3\"]}' and so forth.

# Make sure to chmod +x this file before running. Hvae fun!



declare -A Experiments
Experiments=(
	["Calibration_Fig1"]="--tstart 10 --perc 0.4 --alphae0 0.7 --case1 {\"tend\":13,\"tfinal\":25} --case2 {\"tend\":20,\"tfinal\":35}"
	["PathPhys_Fig2"]="--tstart 200 --tend 500 --tfinal 12 --excite 1 6 30 -s --case1 {\"perc\":0.4} --case2 {\"astblock\":[1,6]}"
	["Pscale_Fig3"]="--tstart 20 --tend 45 --tfinal 80 --perc 0 --pumpScaleNeuron 3 --pumpScaleAst 3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	["ED_Fig3"]="--tstart 20 --tend 45 --tfinal 70 --perc 0.3 --alphae0 0.2 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	)
for name_ in "${!Experiments[@]}"; do
    python set_up.py \
    ${Experiments[$name_]} \
    --solve \
    --keepbranch \
    --casename "FinalFig2211" \
    --saveloc "PaperExp/$name_" --datsave
done;