#!/bin/bash
declare -A ECSsizes
ECSsizes=( ["-s"]="SmallECS"
#           ["-m"]="MedECS"
            ["-b"]="BigECS")

declare -A Experiments
Experiments=(
    ["pED_IClGblock"]="--tstart 20 --tend 50 --perc 0.5  --tfinal 80 --block {\"IClG\":[20,50]}"
	         ["pED_IKGblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"IKG\":[20,50]} --tfinal 80"	
	         ["pED_INaGblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"INaG\":[20,50]} --tfinal 80"
             ["pED_INCXiblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"INCXi\":[20,50]} --tfinal 80 "
             ["pED_INCXgGblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"INCXg\":[20,50]} --tfinal 80"
             ["pED_JKClblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"JKCl\":[20,50]} --tfinal 80"
             ["pED_GLTgblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"fGLTg\":[20,50]} --tfinal 80"
	      ["pED_GLTiblock"]="--tstart 20 --tend 50 --perc 0.5 --block {\"fGLTi\":[20,50]} --tfinal 80"
              ["pED_NKCC1block"]="--tstart 20 --tend 50 --perc 0.5 --block {\"fNKCC1\":[20,50]} --tfinal 80"
	          ["ED_IClGblock"]="--tstart 20 --tend 50 --perc 0.0  --tfinal 80 --block {\"IClG\":[20,50]}"
	         ["ED_IKGblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"IKG\":[20,50]} --tfinal 80"	
	         ["ED_INaGblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"INaG\":[20,50]} --tfinal 80"
             ["ED_INCXiblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"INCXi\":[20,50]} --tfinal 80 "
             ["ED_INCXgGblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"INCXg\":[20,50]} --tfinal 80"
             ["ED_JKClblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"JKCl\":[20,50]} --tfinal 80"
             ["ED_GLTgblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"fGLTg\":[20,50]} --tfinal 80"
	      ["ED_GLTiblock"]="--tstart 20 --tend 50 --perc 0.0 --block {\"fGLTi\":[20,50]} --tfinal 80"
             ["ED_NKCC1block"]="--tstart 20 --tend 50 --perc 0.0 --block {\"fNKCC1\":[20,50]} --tfinal 80"
       	     ["Calibration"]="--tstart 20 --tend 22  --perc 0.4 --alphae0 0.7 --tfinal 50"
	     ["Calibration_GLTn"]="--tstart 20 --tend 22  --perc 0.4 --alphae0 0.7 --tfinal 50 --block {\"fGLTi\":[20,22]}"
	     ["Calibration_GLTg"]="--tstart 20 --tend 22  --perc 0.4 --alphae0 0.7 --tfinal 50 --block {\"fGLTg\":[20,22]}"
                 ["HyperNKA"]="--pumpScaleAst 2 --pumpScaleNeuron 2 --tstart 20 --tend 30 --tfinal 120"
	         ["HyperNKAhalfx"]="--pumpScaleAst 1.8 --pumpScaleNeuron 1.8 --tstart 20 --tend 45 --tfinal 120" 
	         ["HyperNKA3x"]="--pumpScaleAst 3 --pumpScaleNeuron 3 --tstart 20 --tend 35 --tfinal 120"
                 ["HyperNKA3xlonger"]="--pumpScaleAst 3 --pumpScaleNeuron 3 --tstart 20 --tend 45  --tfinal 120"
              ["HealthyResponseShort"]="--tstart 500 --tend 600 --tfinal 4 --excite 1 3"
              ["AstKnockHealthy"]="--tstart 500 --tend 600 --tfinal 30 --excite 1 5 --block {\"fGLTg\":[1,5],\"fGLTi\":[1,5]}"
              ["UnhealthyResponse"]="--tstart 20 --tend 40 --tfinal 100 --excite 60 80"
             ["AstKnockUnhealthy"]="--tstart 20 --tend 40 --tfinal 100 --excite 60 80 --block {\"fGLTg\":[60,100],\"fGLTi\":[60,100]}")

# declare -A Intensity
# Intensity=( ["Lev1"]="0.3"
# 	    ["Lev2"]="0.35"
# 	    ["Lev3"]="0.4"
# 	    ["Lev4"]="0.45"
# 	    ["Lev5"]="0.5"
# 	    ["Lev6"]="0.55"
# 	    ["Lev7"]="0.6"
# 	    ["Lev8"]="0.65"
# 	    ["Lev9"]="0.7"
# 	    ["Lev10"]="0.75"
# 	    ["Lev11"]="0.8"
# 	    ["Lev12"]="0.85")

# declare -A Duration
# Duration=( ["2min"]="22.0"
# 	   ["4min"]="24.0"
# 	   ["6min"]="26.0"
# 	   ["8min"]="28.0"
# 	   ["10min"]="30.0")
	    
# for intensity_ in "${!Intensity[@]}"; do
#   for duration_ in "${!Duration[@]}"; do
#     python set_up.py \
#     --gltScale 2 \
#     --name "$intensity_" \
#     --perc ${Intensity[$intensity_]} \
#     -s \
#     --tstart 20 --tend ${Duration[$duration_]} --tfinal 60 \
#     --solve \
#     --write \
#     --plot '{"MemPot":["Vi","Vg"],"Na":["NaCi","NaCg"],"Glu1":["GluCi","GluCg"],"Glu2":["GluCc"],"Ca":["CaCi","CaCc","CaCg"]}' \
#     --titles '{"MemPot":"Membrane potential (in mV)","Na":"$[Na^+]$ (in mM)","W": "Volume (in pL)", "Glu1": "[Glu] (in mM)","Glu2":"[Glu] (in mM)","Ca":"$[Ca^{2+}]$ (in mM)" }' \
#     --saveloc "$intensity_/$duration_"
#   done; 
# done



for name_ in "${!Experiments[@]}"; do
  for size_ in "${!ECSsizes[@]}"; do
    python set_up.py \
    --name "${ECSsizes[$size_]}" \
    $size_ \
    ${Experiments[$name_]} \
    --solve \
    --write \
    --plot '{"MemPot":["Vi","Vg"],"Na":["NaCi","NaCg"],"Glu1":["GluCi","GluCg"],"Glu2":["GluCc"],"Ca":["CaCi","CaCc","CaCg"]}' \
    --save '{"NaCi":"full","NaCe":"full","NaCg":"full","KCi":"full","KCe":"full","KCg":"full","ClCi":"full","ClCe":"full","ClCg":"full","CaCi":"full","CaCc":"full","CaCg":"full","GluCi":"full","GluCc":"full","GluCg":"full","Voli":"full","Volg":"full","Vi":"full","Vg":"full"}' \
    --titles '{"MemPot":"Membrane potential (in mV)","Na":"$[Na^+]$ (in mM)","W": "Volume (in pL)", "Glu1": "[Glu] (in mM)","Glu2":"[Glu] (in mM)","Ca":"$[Ca^{2+}]$ (in mM)" }' \
    --saveloc "$name_/${ECSsizes[$size_]}"
  done; 
done
