#!/bin/bash

# Calibration
python fm_class.py --name 'Calibration' --saveloc 'Calibration' --ChargeCIgnore  --solve -s --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tstart = 20' 'tend = 21.7' 'perc=0.2' 'tfinal = 40' --plot 'NaCi' 'NaCg' 'KCe' 'CaCi' 'GluCi' 'CaCg'

# Swelling ratio vs energy deprivation and ECS size
python fm_class.py --name 'SmallECSHighOGD' --ChargeCIgnore  --saveloc 'SwellingRatio' --solve -s --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tstart = 20' 'tend = 30' 'perc = 0.1' 'tfinal = 60' --plot 'Wi' 'Wg' 'V' 'Vg' 'NaCi' 'NaCg'
python fm_class.py --name 'SmallECSLowOGD' --ChargeCIgnore  --saveloc 'SwellingRatio' --solve -s --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tstart = 20' 'tend = 30' 'perc = 0.7' 'tfinal = 60' --plot 'Wi' 'Wg' 'V' 'Vg' 'NaCi' 'NaCg'
python fm_class.py --name 'BigECSHighOGD' --ChargeCIgnore  --saveloc 'SwellingRatio' --solve -s --freeparams 'alphae0 = 0.6' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tstart = 20' 'tend = 30' 'perc = 0.1' 'tfinal = 60' --plot 'Wi' 'Wg' 'V' 'Vg' 'NaCi' 'NaCg'
python fm_class.py --name 'BigECSLowOGD' --ChargeCIgnore  --saveloc 'SwellingRatio' --solve -s --freeparams  'alphae0 = 0.6' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tstart = 20' 'tend = 30' 'perc = 0.1' 'tfinal = 60' --plot 'Wi' 'Wg' 'V' 'Vg' 'NaCi' 'NaCg'

# Depolarization and recovery with respect to ECS and baseline pump strength (Brisson and Andrew 2012)
#HyperNKA
python fm_class.py --ChargeCIgnore --name 'SmallECS' --saveloc '1xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS' --saveloc '1xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS' --saveloc '1xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --ChargeCIgnore --name 'SmallECS' --saveloc '3xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS' --saveloc '3xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS' --saveloc '3xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --ChargeCIgnore --name 'SmallECS' --saveloc '8xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS' --saveloc '8xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS' --saveloc '8xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

# Selective blockade




#---------------------------------------------------------------------------------------------------------

# Healthy response to activity in the synaptic cleft


# Astrocyte knockout in healthy excitation to neuron


# OGD 10-20 min


# Stimualtion during unhealthy baseline conditions


# Astrocyte knockout during excitation from baseline pathological state


# NCX activity as predicted (??)
