#!/bin/bash

# Calibration
python fm_class.py --name 'Calibration' --saveloc 'Calibration' --solve -s --freeparams 'tstart = 20' 'tend = 21.7' 'tfinal = 40' --plot 'NaCi' 'NaCg' 'KCe' 

# Swelling ratio vs energy deprivation and ECS size


# Depolarization and recovery with respect to ECS and baseline pump strength (Brisson and Andrew 2012)


# Selective blockade

#---------------------------------------------------------------------------------------------------------

# Healthy response to activity in the synaptic cleft


# Astrocyte knockout in healthy excitation to neuron


# OGD 10-20 min


# Stimualtion during unhealthy baseline conditions


# Astrocyte knockout during excitation from baseline pathological state


# NCX activity as predicted (??)
