#!/bin/bash

# All figures from the paper are simulated here

python set_up.py --solve --saveloc 'Finalfigures/AstrocytePresentExcitation' --savenumpy  --tfinal 16 --excite 1 15 20 10 0.95 --alphae0 0.2  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg","ax2IExcite*p.F/25*7.5-20"],"ax1scale":[-90,40],"ax2scale":[-85,-10]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe","ax1IExcite*p.F/25*1.5+18"],"ax2scale":[145,170],"ax1scale":[5,20]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe","ax1IExcite*p.F/25*8+150"],"ax2scale":[1,12],"ax1scale":[79,160]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We","ax1IExcite*p.F/25*0.52+104"],"ax1scale":[99.5,104.7],"ax2scale":[93,104]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc","ax1IExcite*p.F/25*0.35+3"],"ax1scale":[0,3.5],"ax2scale":[9e-5,7e-4]},"size":[5,1]}'

python set_up.py --solve --saveloc 'Finalfigures/AstrocyteAbsentExcitation' --savenumpy   --tfinal 16 --excite 1 15 20 10 0.95 --astblock 1 15 --alphae0 0.2  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg","ax2IExcite*p.F/25*7.5-20"],"ax1scale":[-90,40],"ax2scale":[-85,-10]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe","ax1IExcite*p.F/25*4+40"],"ax2scale":[100,170],"ax1scale":[5,45]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe","ax1IExcite*p.F/25*8+150"],"ax2scale":[1,60],"ax1scale":[79,160]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We","ax1IExcite*p.F/25*2.05+117"],"ax1scale":[99.5,120],"ax2scale":[70,110]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc","ax1IExcite*p.F/25*0.67+5.5"],"ax1scale":[-0.2,6.5],"ax2scale":[-12e-2,0.12]},"size":[5,1]}'

python set_up.py --solve  --saveloc 'Finalfigures/ShortED' --savenumpy  --alphae0 0.8 --t0 15 --tstart 20 --tend 25 --tfinal 35  --perc 0.5 --plot  '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99.5,130],"ax2scale":[95,100.2]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc 'Finalfigures/LongED' --savenumpy --alphae0 0.8 --t0 15 --tstart 20 --tend 35 --tfinal 45 --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99.5,130],"ax2scale":[95,100.2]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' 

python set_up.py --solve --saveloc  'Finalfigures/VolumeBig' --savenumpy --alphae0 0.8  --tstart 20 --tend 25 --t0 15 --tfinal 55 --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' --beta1 4 --beta2 4 

python set_up.py --solve --saveloc  'Finalfigures/VolumeSmall'--savenumpy --alphae0 0.2  --tstart 20 --tend 25 --t0 15 --tfinal 55 --perc 0.5 --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' 

python set_up.py --solve --saveloc 'Finalfigures/PScale1_BigECS' --savenumpy --t0 15 --alphae0 0.8  --tstart 20 --tend 35 --tfinal 40  --perc 0.0   --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' 

python set_up.py --solve --saveloc 'Finalfigures/PScale1_SmallECS' --savenumpy --t0 15 --alphae0 0.2  --tstart 20 --tend 35 --tfinal 40  --perc 0.0   --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc 'Finalfigures/PScale2_SmallECS' --savenumpy --t0 15 --alphae0 0.2  --tstart 20 --tend 35 --tfinal 50  --perc 0  --pumpScaleNeuron 1.875 --pumpScaleAst 1.875  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc 'Finalfigures/PScale2_BigECS' --savenumpy --t0 15 --alphae0 0.8  --tstart 20 --tend 35 --tfinal 50  --perc 0  --pumpScaleNeuron 1.875 --pumpScaleAst 1.875  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'


python set_up.py --solve --saveloc 'Finalfigures/EAATastrocyteblock' --savenumpy  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'   --alphae0 0.8 --t0 15 --tstart 20 --tend 25 --tfinal 35  --perc 0.5  --block '{"fGLTg":[20,25]}' 

python set_up.py --solve --saveloc 'Finalfigures/NCXblock' --savenumpy  --alphae0 0.8 --t0 15 --tstart 20 --tend 25 --tfinal 35  --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' --block '{"INCXi":[20,25],"INCXg":[20,25]}' 

python set_up.py --solve --saveloc 'Finalfigures/INaGblock' --savenumpy  --alphae0 0.8 --tstart 20 --tend 25 --tfinal 35 --t0 15  --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"],"ax1scale":[-81,14]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' --beta1 4 --beta2 4 --block '{"INaG":[20,25]}' 

python set_up.py --solve --saveloc 'Finalfigures/INaGblockPost' --savenumpy  --alphae0 0.8 --t0 15 --tstart 20 --tend 35 --tfinal 60  --perc 0.5   --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' --beta1 4 --beta2 4 --block '{"INaG":[45,55]}' 


# Extra figures for bifrcations

python set_up.py --solve --saveloc  'Finalfigures/VolumeBig_Longer' --savenumpy --alphae0 0.8  --tstart 20 --tend 35 --t0 15 --tfinal 200 --perc 0.5 --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc  'Finalfigures/VolumeSmall_Longer' --savenumpy --alphae0 0.2  --tstart 20 --tend 35 --t0 15 --tfinal 200 --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc  'Finalfigures/VolumeBig_Bif' --savenumpy --alphae0 0.8  --tstart 20 --tend 25 --t0 15 --tfinal 200 --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}'

python set_up.py --solve --saveloc  'Finalfigures/VolumeSmall_Bif' --savenumpy --alphae0 0.2  --tstart 20 --tend 25 --t0 15 --tfinal 200 --perc 0.5  --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax2Vg"]},"[Na$^+$] (mM)":{"plot":["ax1NaCi","ax1NaCg","ax2NaCe"]},"[K$^+$] (mM)":{"plot":["ax1KCi","ax1KCg","ax2KCe"]},"Volume (%)":{"plot":["ax1Voli","ax1Volg","ax21/p.We0*100*We"],"ax1scale":[99,121],"ax2scale":[30,105]},"[Glu] (mM)":{"plot":["ax1GluCi","ax1GluCg","ax2GluCc"]},"size":[5,1]}' 


# Supplementary figures

python set_up.py --solve --saveloc 'Finalfigures/SuppFigExcite' --casename 'Excite' --case1 '{"excite":[1,15,20,10,0.95]}' --case2 '{"excite":[1,15,20,10,0.95],"astblock":[1,15]}' --alphae0 0.2 --t0 0 --tfinal 20  --tstart 100 --tend 200 --perc 0.9 

python set_up.py --solve --saveloc 'Finalfigures/SuppFig2' --casename 'ED' --case1 '{"tstart":20,"tend":25}' --case2 '{"tstart":20,"tend":30}' --alphae0 0.8  --tfinal 50  --perc 0.5 --nogates

# python set_up.py --solve --saveloc 'Finalfigures/SuppFig3GD' --case1 '{"tstart":20,"tend":25}' --plotall --alphae0 0.8 --t0 0 --tfinal 200 --tstart 20 --tend 500  --perc 0 --gltScale 0.1 --gltScaleAst 2 --pumpScaleNeuron 1.6 --pumpScaleAst 1.6

python -i set_up.py --solve --readdata 'Finalfigures/SynapticRecovery' --alphae0 0.8 --tstart 5 --tend 20 --excite 30 44 20 10 0.95 --block '{"INaG":[55,65]}' --t0 30 --excite2 120 134 20 10 0.95 --tfinal  --perc 0.5   --plot '{"E$_m$ (mV)":{"plot":["ax1Vi","ax1IExcite*p.F/25*10+15.5","ax1IExcite2*p.F/25*10+15.5"]},"[Glu] (mM)":{"plot":["ax1GluCc"]},"size":[2,1]}' --beta1 4 --beta2 4


