#!/bin/bash
declare -A Experiments
Experiments=(
	["Calibration_Fig1"]="--tstart 10 --perc 0.4 --alphae0 0.7 --case1 {\"tend\":13,\"tfinal\":20} --case2 {\"tend\":20,\"tfinal\":30}"
	["PathPhys_Fig2"]="--tstart 200 --tend 500 --tfinal 7 --excite 1 6 -s --case1 {\"perc\":0.4} --case2 {\"astblock\":[1,6]}"
	["ED_Fig3"]="--tstart 20 --tend 45 --tfinal 70 --perc 0.3 --alphae0 0.2 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	["Pscale_baseline_Fig4"]="--tstart 20 --tend 170 --tfinal 200 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	["Pscale_1.5x_Fig5"]="--tstart 20 --tend 170 --tfinal 200 --pumpScaleNeuron 2.2 --pumpScaleAst 2.2 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	["Pscale_2x_Fig6"]="--tstart 20 --tend 170 --tfinal 200 --pumpScaleNeuron 3 --pumpScaleAst 3 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
	)
for name_ in "${!Experiments[@]}"; do
    python set_up.py \
    ${Experiments[$name_]} \
    --solve \
    --casename "Baseline_GLTi" \
    --saveloc "PaperExp/$name_"
done;
