#!/bin/bash
# declare -A Experiments
# Experiments=(
# 	#["Calibration_Fig1"]="--tstart 10 --perc 0.4 --alphae0 0.7 --case1 {\"tend\":13,\"tfinal\":20} --case2 {\"tend\":20,\"tfinal\":30}"
# 	#["PathPhys_Fig2"]="--tstart 200 --tend 500 --tfinal 7 --excite 1 6 -s --case1 {\"perc\":0.4} --case2 {\"astblock\":[1,6]}"
# 	#["ED_Fig3"]="--tstart 20 --tend 45 --tfinal 70 --perc 0.3 --alphae0 0.2 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
# 	#["Pscale_baseline_Fig4"]="--tstart 20 --tend 170 --tfinal 200 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
# 	["Pscale_1.5x_Fig5"]="--tstart 20 --tend 200 --tfinal 350 --pumpScaleNeuron 2.2 --pumpScaleAst 2.2 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98} --datsave"
# 	#["Pscale_2x_Fig6"]="--tstart 20 --tend 170 --tfinal 200 --pumpScaleNeuron 3 --pumpScaleAst 3 --perc 0.3 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}"
# 	)
# for name_ in "${!Experiments[@]}"; do
#     python set_up.py \
#     ${Experiments[$name_]} \
#     --solve \
#     --casename "Baseline_GLTi" \
#     --saveloc "PaperExp/$name_"
# done;

# python PScale_tED_vs_alphae.py
# #python minNKA_vs_tED.py
# python recovery.py	       

declare -A Experiments
Experiments=(
    ["Bistability"]="--tstart 10 --perc 0.4 --alphae0 0.7 --case1 {\"tend\":13,\"tfinal\":20} --case2 {\"tend\":20,\"tfinal\":30}"
    ["EDref1"]="--tstart 10 --tend 20 --tfinal 50 --perc 0.5 --alphae0 0.75 --plotall"
    ["EDref2"]="--tstart 10 --tend 20  --tfinal 50 --perc 0.6 --alphae0 0.75 --plotall"
    ["EDref3"]="--tstart 10 --tend 20  --tfinal 50 --perc 0.55 --alphae0 0.75 --plotall"
    ["EDref4"]="--tstart 10 --tend 20  --perc 0.55 --tfinal 50 --alphae0 0.75 --plotall"
	["PathPhys_Fig2"]="--tstart 200 --tend 500 --tfinal 7 --excite 1 6 -s --case1 {\"perc\":0.4} --case2 {\"astblock\":[1,6]}  --casename \"GLTi0.1\""
	["ED_Fig3"]="--tstart 20 --tend 45 --tfinal 70 --perc 0.3 --alphae0 0.2 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}  --casename \"GLTi0.1\""
	["Pscale1"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.3 --pumpScaleAst 2.3 -b --plotall"
	["Pscale2"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.5 --pumpScaleAst 2.5 -b --plotall"
	["Pscale3"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.7 --pumpScaleAst 2.7 -b --plotall"
	["Pscale4"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 3 --pumpScaleAst 3 -b --plotall"
	)
for name_ in "${!Experiments[@]}"; do
    python set_up.py \
    ${Experiments[$name_]} \
    --solve \
    --gltScale 0.1 \
    --saveloc "FinalExp/$name_"
done;

declare -A Experiments
Experiments=(
    # ["Bistability"]="--tstart 10 --perc 0.4 --alphae0 0.7 --case1 {\"tend\":13,\"tfinal\":20} --case2 {\"tend\":20,\"tfinal\":30}"
    ["EDref1"]="--tstart 10 --tend 20 --tfinal 50 --perc 0.5 --alphae0 0.8 --plotall"
    ["EDref2"]="--tstart 10 --tend 20  --tfinal 50 --perc 0.45 --alphae0 0.8 --plotall"
    ["EDref3"]="--tstart 10 --tend 20  --tfinal 50 --perc 0.55 --alphae0 0.8 --plotall"
     ["EDref4"]="--tstart 10 --perc 0.55 --alphae0 0.75 --plotall"
	# ["PathPhys_Fig2"]="--tstart 200 --tend 500 --tfinal 7 --excite 1 6 -s --case1 {\"perc\":0.4} --case2 {\"astblock\":[1,6]}  --casename \"GLTi0.1\""
	# ["ED_Fig3"]="--tstart 20 --tend 45 --tfinal 70 --perc 0.3 --alphae0 0.2 --case1 {\"alphae0\":0.2} --case2 {\"alphae0\":0.98}  --casename \"GLTi0.1\""
	# ["Pscale1"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.3 --pumpScaleAst 2.3 -b --plotall"
	# ["Pscale2"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.5 --pumpScaleAst 2.5 -b --plotall"
	# ["Pscale3"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 2.7 --pumpScaleAst 2.7 -b --plotall"
	# ["Pscale4"]="--tstart 20 --tend 45 --tfinal 100 --perc 0.2 --pumpScaleNeuron 3 --pumpScaleAst 3 -b --plotall"
	)
for name_ in "${!Experiments[@]}"; do
    python set_up.py \
    ${Experiments[$name_]} \
    --solve \
    --gltScale 0.1 \
    --saveloc "ExtraExp/$name_"
done;
