#!/bin/bash

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Selective blockade 2

#python fm_class.py --name 'OrigSmallECS_BlockNaAstrocyte' --solve --write -s --block '{"fNKCC1":[70,120], "fGLTg":[70,120],"INCXg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
#python fm_class.py --name 'OrigSmallECS_BlockCl' --solve --write -s --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

#python fm_class.py --name 'OrigBigECS_BlockNaAstrocyte' --solve --write -b --block '{"fNKCC1":[70,120], "fGLTg":[70,120],"INCXg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
#python fm_class.py --name 'OrigBigECS_BlockCl' --solve --write -b --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

#git add -A
#git commit -m SelectiveBlockade2
#git push

# Block leaks
python fm_class.py --name 'OrigSmallECS_BlockNaLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'OrigSmallECS_BlockClLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'OrigBigECS_BlockNaLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'OrigBigECS_BlockClLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Changed pathological Na 

#PathNaChanged
python fm_class.py  --ChargeCIgnore --solve -s --name 'PathNaChanged'  --freeparams 'tstart=20' 'tend = 25' 'tfinal = 50' 'nkccScale=10' 'gltScale=2' 'ncxScale=1' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'NaCg' 'KCg' 'ClCg' 'NaCi' 'KCi' 'ClCi'

#HyperNKA
python fm_class.py --ChargeCIgnore --name 'SmallECS_1xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS_1xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS_1xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --ChargeCIgnore --name 'SmallECS_3xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS_3xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS_3xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'   'pumpScaleNeuron = 3' 'pumpScaleAst = 3'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --ChargeCIgnore --name 'SmallECS_8xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'MedECS_8xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --ChargeCIgnore --name 'BigECS_8xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'gltScale=2'  'pumpScaleNeuron = 8' 'pumpScaleAst = 8'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

git add -A
git commit -m ChangedParHyperNKA
git push

#SelectiveBlockade
#Selective blockade experiments
python fm_class.py --name 'SmallECS_BlockINaG' --solve --write -s --block '{"INaG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2'n  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIKG' --solve --write -s --block '{"IKG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIClG' --solve --write -s --block '{"IClG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockJKCl' --solve --write -s --block '{"JKCl":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockINCXi' --solve --write -s --block '{"INCXi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfGLTi' --solve --write -s --block '{"fGLTi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIKir' --solve --write -s --block '{"IKir":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockINCXg' --solve --write -s --block '{"INCXg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfGLTg' --solve --write -s --block '{"fGLTg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfNKCC1' --solve --write -s --block '{"fNKCC1":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockWateri' --solve --write -s --block '{"Wateri":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockWaterg' --solve --write -s --block '{"Waterg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'BigECS_BlockINaG' --solve --write -b --block '{"INaG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIKG' --solve --write -b --block '{"IKG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIClG' --solve --write -b --block '{"IClG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockJKCl' --solve --write -b --block '{"JKCl":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BIgECS_BlockINCXi' --solve --write -b --block '{"INCXi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfGLTi' --solve --write -b --block '{"fGLTi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIKir' --solve --write -b --block '{"IKir":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BIgECS_BlockINCXg' --solve --write -b --block '{"INCXg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfGLTg' --solve --write -b --block '{"fGLTg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfNKCC1' --solve --write -b --block '{"fNKCC1":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockWateri' --solve --write -b --block '{"Wateri":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockWaterg' --solve --write -b --block '{"Waterg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'SmallECS_BlockNaLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockClLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'BigECS_BlockNaLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockClLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'SmallECS_BlockNaAstrocyte' --solve --write -s --block '{"fNKCC1":[70,120], "fGLTg":[70,120],"INCXg":[70,120]}' --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockCl' --solve --write -s --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'BigECS_BlockNaAstrocyte' --solve --write -b --block '{"fNKCC1":[70,120], "fGLTg":[70,120],"INCXg":[70,120]}' --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockCl' --solve --write -b --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'gltScale=2' 'pumpScaleAst = 2' 'pumpScaleNeuron=2' 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

git add -A
git commit -m ChangedParSelectiveBlockade
git push


#Calibration
#python fm_class.py --name 'calibration3' --solve -s --freeparams 'tend=40' 'tfinal=100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'perc = 0.2' 'Wg0 = 1.7' --plot 'KCe' 'NaCi' 'NaCg' 'INCXi' 'INCXg'

# Astblock and Excite experiment
python fm_class.py --name 'OrigSmallECS_ExciteFromHealthy' --solve --write -s --excite 0.0 30.0 --freeparams 'tfinal=30' 'tstart=500' 'tend=501' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigBigECS_ExciteFromHealthy' --solve --write -b --excite 0.0 30.0  --freeparams 'tfinal=30' 'tstart=500' 'tend=501' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigSmallECS_ExciteFromUnhealthy' --solve --write -s --excite 40.0 50.0 --freeparams 'tfinal=50' 'tstart=20' 'tend=25' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigBigECS_ExciteFromUnhealthy' --solve --write -b --excite 40.0 50.0   --freeparams 'tfinal=50' 'tstart=20' 'tend=25' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigSmallECS_ExciteWhenUnhealthy' --solve --write -s --excite 100.0 110.0  --freeparams 'tfinal=110' 'tstart=20' 'tend=110' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigBigECS_ExciteWhenUnhealthy' --solve --write -b --excite 100.0 110.0  --freeparams 'tfinal=110' 'tstart=20' 'tend=110' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigSmallECS_AstblockExciteFromHealthy' --solve --write -s --excite 0.0 10.0 --astblock 5.0 10.0 --freeparams 'tfinal=10' 'tstart=500' 'tend=501' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'
python fm_class.py --name 'OrigBigECS_AstblockExciteFromHealthy' --solve --write -b --excite 0.0 10.0  --astblock 5.0 10.0 --freeparams 'tfinal=10' 'tstart=500' 'tend=501' --plot 'V' 'Vg' 'GluCi' 'GluCg' 'GluCc' 'CaCi' 'CaCg' 'CaCc'

git add -A
git commit -m AstblockExcite
git push

