#!/bin/bash
declare -A ECSsizes
ECSsizes=( ["-s"]="SmallECS"
           ["-m"]="MedECS"
           ["-b"]="BigECS")

declare -A Experiments
Experiments=( ["IClGblock"]="--tstart 20 --tend 40  --tfinal 180 --block {\"IClG\":[100,120]}"
	          ["IKGblock"]="--tstart 20 --tend 40 --block {\"IKG\":[100,120]} --tfinal 180"	
	          ["INaGblock"]="--tstart 20 --tend 40 --block {\"INaG\":[100,120]} --tfinal 180"
              ["INCXiblock"]="--tstart 20 --tend 40 --block {\"INCXi\":[100,120]} --tfinal 180"
              ["INCXgGblock"]="--tstart 20 --tend 40 --block {\"INCXg\":[100,120]} --tfinal 180"
              ["JKClblock"]="--tstart 20 --tend 40 --block {\"JKCl\":[100,120]} --tfinal 180"
              ["GLTgblock"]="--tstart 20 --tend 40 --block {\"fGLTg\":[100,120]} --tfinal 180"
              ["NKCC1block"]="--tstart 20 --tend 40 --block {\"fNKCC1\":[100,120]} --tfinal 180"
              ["SwellingRatio"]="--tstart 20 --tend 30 --perc 0.1 --tfinal 60"
              ["HyperNKA"]="--tstart 20 --tend 60 --tfinal 120"
	          ["HyperNKA3x"]="--pumpScaleAst 3 --pumpScaleNeuron 3 --tstart 20 --tend 60 --tfinal 120"
	          ["HyperNKA8x"]="--pumpScaleAst 8 --pumpScaleNeuron 8 --tstart 20 --tend 60 --tfinal 120"
              ["HealthyResponse"]="--tstart 500 --tend 600 --tfinal 30 --excite 0 20 "
              ["AstKnockHealthy"]="--tstart 500 --tend 600 --tfinal 30 --excite 0 20 --astblock 10 30"
              ["UnhealthyResponse"]="--tstart 20 --tend 40 --tfinal 100 --excite 60 80"
              ["AstKnockUnhealthy"]="--tstart 20 --tend 40 --tfinal 100 --excite 60 80 --astblock 60 100")


for name_ in "${!Experiments[@]}"; do
  for size_ in "${!ECSsizes[@]}"; do
    python fm_class.py \
    --gltScale 2 --pumpScaleAst 2 --pumpScaleNeuron 2 --nogates \
    --name "${ECSsizes[$size_]}" \
    ${Experiments[$name_]} \
    $size_ \
    --solve \
    --write \
    --plot '{"KCe":["KCe"],"MemPot":["Vi","Vg"],"Na":["NaCi","NaCg"],"W":["Wi","Wg"],"Glu":["GluCi","GluCc","GluCg"],"Ca":["CaCi","CaCc","CaCg"]}' \
    --titles '{"KCe":" $[K^+]$ (in mM)", "MemPot":"Membrane potential (in mV)","Na":"$[Na^+]$ (in mM)","W": "Volume (in pL)", "Glu": "[Glu] (in mM)","Ca":"$[Ca^{2+}]$ (in mM)" }' \
    --saveloc "$name_/${ECSsizes[$size_]}"
  done; 
done
