#!/bin/bash

# Baseline pump strength and extracellular space
python fm_class.py --name 'smallAsts' --solve --write -s --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' 'Wg0 = 0.2*1.7' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'
#python fm_class.py --name 'normalAsts' --solve --write -s --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'
python fm_class.py --name 'smallAstm' --solve --write -m --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' 'Wg0 = 0.2*1.7' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'
#python fm_class.py --name 'normalAstm' --solve --write -m --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'
python fm_class.py --name 'smallAstb' --solve --write -b --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' 'Wg0 = 0.2*1.7' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'
#python fm_class.py --name 'normalAstb' --solve --write -b --freeparams 'tend = 60' 'tfinal = 100' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'

#python fm_class.py --name 'NoAstExp31' --solve --write -s --freeparams 'tend = 60' 'tfinal = 100' 'astroblock=1' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'

#python fm_class.py --name 'NoAstExp21' --solve --write -m --freeparams 'tend = 60' 'tfinal = 100' 'astroblock=1' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'

#python fm_class.py --name 'NoAstExp11' --solve --write -b --freeparams 'tend = 60' 'tfinal = 100' 'astroblock=1' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg' 'Wi' 'Wg'



#python fm_class.py --name 'midExp1_1' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 8' 'pumpScaleAst = 8' 'gltScale = 5' 'kirScale = 100' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp1_2' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 8' 'pumpScaleAst = 8' 'gltScale = 5' 'kirScale = 100' 'astroblock=1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp2_1' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 2' 'pumpScaleAst = 2' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp2_2' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 2' 'pumpScaleAst = 2' 'gltScale = 1' 'kirScale = 1' 'astroblock=1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp3_1' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 3' 'pumpScaleAst = 3' 'gltScale = 1' 'kirScale = 1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
#python fm_class.py --name 'midExp3_2' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 3' 'pumpScaleAst = 3' 'gltScale = 1' 'kirScale = 1' 'astroblock=1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp4_1' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1'  --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'
# python fm_class.py --name 'midExp4_2' --solve --write -m --freeparams 'tend = 80' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'gltScale = 1' 'kirScale = 1' 'astroblock=1' --plot 'KCe' 'NaCg' 'NaCi' 'V' 'Vg' 'GluCi' 'GluCg' 'CaCi' 'CaCg'

# Sensitivity and recovery




#Calibration
# python fm_class.py --name 'calibration3' --solve -s --freeparams 'tend=22' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'perc = 0.2' --plot 'KCe' 'NaCi' 'NaCg' 

#python fm_class.py --name 'calibration3' --solve -s --freeparams 'tend=30' 'pumpScaleNeuron = 1' 'pumpScaleAst = 1' 'perc = 0.2' --plot 'KCe' 'NaCi' 'NaCg' 
