#!/bin/bash
declare -A ECSsizes
ECSsizes=( ["-s"]="SmallECS"
           ["-m"]="MedECS"
           ["-b"]="BigECS")

declare -A Experiments
Experiments=( ["SwellingRatio"]="--tstart 20
                                 --tend 30 --perc 0.1 --tfinal 60 --excite 0 0.5 --nogates"
              ["HyperNKA"]="--tstart 20 --tend 60 --tfinal 120 --nogates")


for name_ in "${!Experiments[@]}"; do
  for size_ in "${!ECSsizes[@]}"; do
    python fm_class.py \
    --gltScale 2 --pumpScaleAst 2 --pumpScaleNeuron 2  --nochargecons \
    --name "${ECSsizes[$size_]}" \
    ${Experiments[$name_]} \
    $size \
    --solve \
    --write \
    --plot '{"KCe":["KCe"],"MemPot":["Vi","Vg"],"Na":["NaCi","NaCg"],"W":["Wi","Wg"],"Glu":["GluCi","GluCc","GluCg"]}' \
    --titles '{"KCe":" $[K^+]$ (in mM)", "MemPot":"Membrane potential (in mV)","Na":"$[Na^]+$ (in mM)","W": "Volume (in pL)", "Glu": "[Glu] (in mM)" }' \
    --saveloc "$name_/${ECSsizes[$size_]}"
  done; 
done
