#!/bin/bash

#Selective blockade experiments
python fm_class.py --name 'SmallECS_BlockINaG' --solve --write -s --block '{"INaG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIKG' --solve --write -s --block '{"IKG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIClG' --solve --write -s --block '{"IClG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockJKCl' --solve --write -s --block '{"JKCl":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockINCXi' --solve --write -s --block '{"INCXi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfGLTi' --solve --write -s --block '{"fGLTi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockIKir' --solve --write -s --block '{"IKir":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockINCXg' --solve --write -s --block '{"INCXg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfGLTg' --solve --write -s --block '{"fGLTg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockfNKCC1' --solve --write -s --block '{"fNKCC1":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockWateri' --solve --write -s --block '{"Wateri":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockWaterg' --solve --write -s --block '{"Waterg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'BigECS_BlockINaG' --solve --write -b --block '{"INaG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIKG' --solve --write -b --block '{"IKG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIClG' --solve --write -b --block '{"IClG":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockJKCl' --solve --write -b --block '{"JKCl":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BIgECS_BlockINCXi' --solve --write -b --block '{"INCXi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfGLTi' --solve --write -b --block '{"fGLTi":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockIKir' --solve --write -b --block '{"IKir":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BIgECS_BlockINCXg' --solve --write -b --block '{"INCXg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfGLTg' --solve --write -b --block '{"fGLTg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockfNKCC1' --solve --write -b --block '{"fNKCC1":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockWateri' --solve --write -b --block '{"Wateri":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockWaterg' --solve --write -b --block '{"Waterg":[70,90]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'SmallECS_BlockNaLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'SmallECS_BlockClLeaks' --solve --write -s --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'

python fm_class.py --name 'BigECS_BlockNaLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "fGLTg":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
python fm_class.py --name 'BigECS_BlockClLeaks' --solve --write -b --block '{"fNKCC1":[70,120], "IClG":[70,120], "JKCl":[70,120]}' --freeparams 'tfinal=150' 'tstart=20' 'tend=40' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'KCe'
