#!/bin/bash

#Baseline pump strength and ECS
python fm_class.py --name 'SmallECS_1xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'MedECS_1xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'BigECS_1xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --name 'SmallECS_3xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'MedECS_3xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 3' 'pumpScaleAst = 3' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'BigECS_3xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 3' 'pumpScaleAst = 3'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

python fm_class.py --name 'SmallECS_8xNKA' --solve --write -s --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'MedECS_8xNKA' --solve --write -m --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 8' 'pumpScaleAst = 8' --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'
python fm_class.py --name 'BigECS_8xNKA' --solve --write -b --freeparams 'tfinal=150' 'tstart=20' 'tend=60' 'pumpScaleNeuron = 8' 'pumpScaleAst = 8'  --plot 'V' 'Vg' 'NaCi' 'NaCg' 'GluCi' 'GluCg' 'GluCc' 'KCe'

